services:
  api:
    container_name: api_ts
    image: api_ts
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_USER=correamito
      - DB_PASSWORD=090903
      - DB_HOST=db
      - DB_PORT=5432
      - DB=users_database
    depends_on:
      - db
  db:
    container_name: users_database
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=correamito
      - POSTGRES_PASSWORD=090903
      - POSTGRES_DB=users_database
